import React from 'react'
const About = () => {
    return(<div>
        About Page

        "Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit..."
"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain..."
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer mattis neque nec cursus lobortis. Aenean non sapien et nibh vehicula tincidunt id et nisl. Duis eu elit consectetur, imperdiet ligula vitae, dignissim mauris. Morbi in auctor enim. Quisque magna justo, mattis sit amet lorem vitae, venenatis vulputate odio. Sed mi lectus, commodo at dui vitae, finibus vestibulum mauris. Curabitur tempor suscipit orci, quis tristique ex fringilla in.

Sed dictum leo libero, quis porta velit convallis nec. Mauris commodo luctus quam eu accumsan. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer dolor metus, placerat nec quam nec, tincidunt tempor erat. Morbi id nulla at metus rhoncus pharetra at quis tellus. Vivamus sed lectus bibendum, vehicula tellus quis, ultricies neque. Nullam vitae gravida lectus. In imperdiet gravida ipsum, et fringilla lorem tincidunt sed. Nulla pulvinar massa id congue cursus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi vehicula neque quis urna sollicitudin blandit. Etiam facilisis arcu laoreet ipsum fermentum porta.

Aliquam erat volutpat. Cras fermentum velit vel magna imperdiet, quis eleifend dolor varius. Donec fermentum tempus tellus, in vulputate ex aliquam at. Etiam laoreet pulvinar finibus. Nullam ac posuere erat, scelerisque lobortis odio. Aliquam feugiat tempor leo, id sollicitudin quam iaculis et. Nam volutpat feugiat eleifend. Curabitur felis lorem, ultricies vel suscipit quis, molestie ut tellus. Nunc congue augue non erat ullamcorper sodales.

Suspendisse ut odio molestie, sollicitudin lacus nec, dignissim tortor. Etiam non augue varius, efficitur ligula in, placerat tortor. Suspendisse potenti. Cras vel interdum odio, at ornare sem. Suspendisse rhoncus in arcu eu ullamcorper. Etiam a semper lorem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aenean magna ex, vehicula sit amet interdum a, iaculis in purus. Nullam volutpat nibh varius lorem tincidunt, in luctus elit pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Curabitur scelerisque velit ac est hendrerit, quis accumsan lacus blandit. Aenean libero ipsum, finibus vitae ligula in, rutrum tempor leo. Nam dictum id ex efficitur eleifend. Integer tempus mollis facilisis. Pellentesque a mollis nunc, eget ultricies nibh. In venenatis dolor quam, ac ornare ipsum interdum in. Nullam efficitur purus tellus, ut ultrices ipsum congue vitae. Ut id massa a ligula volutpat varius. Nulla viverra ornare purus, quis consectetur urna. Proin nec pretium tellus.

Ut metus elit, convallis ac dui ac, lacinia dictum neque. Etiam consectetur id nibh sed sagittis. Donec non sem lectus. Praesent elementum, mauris sed feugiat bibendum, erat erat volutpat nibh, nec dictum mi felis non erat. In ornare lacus ut laoreet mollis. Integer sollicitudin lorem nisi, eu consequat mauris pulvinar a. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a convallis ligula. Pellentesque pharetra luctus ligula vel malesuada. Morbi sodales neque felis, nec egestas risus porttitor quis. Sed quis eros varius, malesuada tortor at, congue arcu. Donec neque lectus, bibendum nec imperdiet eu, mattis eget magna.

Nullam sed enim nisi. Suspendisse potenti. Fusce tincidunt, elit et mattis pharetra, odio dolor elementum metus, et facilisis libero ante posuere tellus. Aenean rhoncus non tortor sit amet dapibus. Integer euismod dapibus tortor, ac tempor arcu placerat vel. Integer elementum sagittis lectus, et aliquam libero pulvinar ac. Suspendisse commodo orci vel sodales posuere. Morbi ut eros nisl. Fusce tincidunt justo nec commodo facilisis. Phasellus dapibus maximus tortor, et lobortis augue egestas ut. Cras dignissim justo sed odio tincidunt consectetur.

Aliquam et mattis tortor, gravida lacinia sem. Aliquam interdum vitae est a viverra. Duis at consectetur mauris, vitae tincidunt sem. Morbi sed erat sit amet magna semper consequat. Donec convallis justo nunc, nec viverra elit interdum id. Nunc ut nulla nunc. Curabitur nisl urna, vestibulum eget imperdiet sit amet, molestie ac ex. In hac habitasse platea dictumst. Vivamus egestas facilisis lorem in aliquam. Donec dignissim dolor at iaculis euismod. Donec et finibus urna. Aliquam erat volutpat.

Fusce hendrerit ut sem ac molestie. Maecenas eget nulla id dolor egestas elementum. Mauris rhoncus quam id orci pretium, in consequat urna vehicula. Nam consequat, tortor vitae condimentum eleifend, erat nisl sollicitudin eros, et pharetra augue orci vel nisi. Praesent turpis nisi, tempus eget iaculis mattis, aliquet a dolor. Sed lacus ipsum, sodales vitae orci vitae, ornare consequat ex. Phasellus sollicitudin risus vel ante scelerisque volutpat. Praesent varius pretium consequat. Etiam efficitur ornare dui, eget bibendum augue pharetra at. Duis viverra tortor quis lacus ullamcorper rhoncus. Quisque fermentum quis nisl vitae maximus. In in urna odio. Etiam sagittis turpis nec egestas sollicitudin. Fusce sed dui in dui vulputate elementum. Vestibulum id tempor est. Cras efficitur turpis id fringilla accumsan.

Nunc porta accumsan sollicitudin. Pellentesque quis dictum turpis, ac consequat est. In nec ligula lectus. Nullam venenatis erat a ipsum consequat aliquam sit amet eu ante. Aliquam pellentesque turpis ac vulputate fringilla. Aliquam tortor elit, molestie ac lacinia ac, auctor vel lacus. Vestibulum ex mauris, mollis vitae condimentum ut, condimentum vel nisi. Suspendisse suscipit nibh erat, id elementum felis volutpat non. Phasellus quis dui eget lectus ornare ultricies commodo vitae magna. Nullam vehicula in ipsum in dictum. Nunc vel ex et purus hendrerit efficitur ut ut magna.

Aliquam luctus eros eu vehicula condimentum. Fusce ac eleifend nunc, eget dapibus metus. Fusce dictum eleifend ultricies. Mauris elementum nunc leo, vel consequat quam dapibus vel. Cras non dictum nisl. Quisque convallis vehicula hendrerit. Phasellus vitae placerat urna. Suspendisse imperdiet justo accumsan, rhoncus odio ornare, tincidunt leo. Vestibulum dictum egestas augue eu ornare. Proin semper euismod elit.

Suspendisse at arcu a risus commodo pharetra at nec ipsum. Phasellus vel congue neque. Ut consequat consectetur metus in cursus. Nam vestibulum finibus viverra. Maecenas sollicitudin purus non accumsan porta. Cras in imperdiet velit. Etiam quis sem aliquam, tempor nulla id, tincidunt urna. In hac habitasse platea dictumst. Nunc et eros mi. Aenean sit amet diam varius, hendrerit mauris facilisis, tempus arcu. Pellentesque pretium ex velit, eget faucibus libero faucibus condimentum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Curabitur eget vehicula erat. Nunc feugiat, quam posuere pharetra ornare, metus nisi malesuada dui, nec imperdiet tellus ipsum et nisl. Cras pellentesque purus ac metus tincidunt, vel molestie lorem congue. Morbi quis ex blandit sem commodo elementum. Sed ultricies finibus diam id hendrerit. Nulla hendrerit lobortis nibh non pharetra. Aliquam erat volutpat. Proin elit justo, porta quis suscipit quis, pulvinar sit amet magna. In hac habitasse platea dictumst. Mauris volutpat posuere elit. Nullam erat sapien, elementum in pellentesque in, fringilla a purus.

Nam ac luctus elit, eu mollis nisl. Fusce elementum, augue eget vulputate mollis, nibh neque faucibus nisl, ut mattis augue purus id ex. Sed sit amet dolor arcu. Fusce euismod mattis pellentesque. Maecenas vitae semper risus, et interdum purus. Aliquam ultricies elementum neque sollicitudin elementum. Curabitur non ante nec velit facilisis bibendum ut sit amet odio. Integer eu cursus velit. Donec sagittis ipsum eget eleifend consectetur. Integer vulputate pulvinar ex eu sagittis. Duis sodales massa sed lobortis commodo. Aenean sit amet rhoncus eros. Proin vel ipsum ultrices, aliquam urna nec, luctus leo. Praesent et erat accumsan, scelerisque mauris rutrum, vestibulum nunc. Morbi porttitor magna odio, in laoreet dolor imperdiet sed.

Sed mollis pellentesque felis nec faucibus. Nam semper tempor neque, vel placerat nisl mollis at. Curabitur hendrerit, nisi vitae molestie sagittis, nibh lectus ornare nisi, ac finibus sapien dolor sagittis est. In dapibus tempus nulla nec aliquam. Fusce vel nisi ligula. Proin nibh risus, rhoncus eget enim eu, rhoncus tristique orci. Sed rhoncus tellus sit amet accumsan scelerisque. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec sagittis lacus a felis fringilla, eu semper sem faucibus. Donec ornare nulla quis orci pellentesque, non pulvinar libero consequat. Nullam sit amet sapien pulvinar dui porttitor posuere. Quisque scelerisque tincidunt posuere. Proin sem neque, ornare quis erat vel, tempus sodales sapien.

Aliquam et felis nec purus imperdiet malesuada ut vitae enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi vulputate tellus felis, id accumsan ligula pretium aliquet. Maecenas venenatis vitae est vel lobortis. Aliquam non nibh justo. Cras nunc ante, cursus at enim sit amet, elementum suscipit lorem. Aliquam ac viverra quam.

Vestibulum magna orci, commodo ac placerat et, laoreet quis augue. Nullam tempus ultricies enim eu sodales. Cras sagittis purus a ultrices rhoncus. Maecenas ultricies, ex a commodo varius, urna ligula tristique orci, eget tristique tortor dolor sed mi. Etiam vitae convallis nisl, eget accumsan arcu. Donec sed magna nisl. Phasellus feugiat odio in orci pharetra, vitae posuere urna congue.

Cras pretium eleifend orci, eu ornare ipsum aliquam nec. Vestibulum eleifend rutrum magna. In placerat imperdiet ante, et convallis mauris vehicula sed. Nullam neque quam, fringilla a ante sit amet, interdum iaculis ex. Etiam ac diam id velit consequat mollis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed dictum volutpat imperdiet. Sed ut turpis tristique, laoreet tortor vel, commodo elit. Phasellus rhoncus sit amet leo vel semper. Pellentesque cursus, nibh sed malesuada posuere, sem elit finibus lectus, ut egestas ligula nulla ut ipsum. Sed tempor, magna in gravida hendrerit, odio dolor mattis justo, tristique tempor odio libero id purus. Cras et efficitur ligula, eget finibus diam. Sed dapibus arcu eu purus commodo ullamcorper. Nulla efficitur enim purus, vel consequat quam pulvinar et.

Curabitur vel porttitor massa. Maecenas placerat diam et justo gravida, quis vulputate ante ornare. Phasellus euismod convallis dictum. Sed imperdiet sapien ante, in mattis arcu sollicitudin a. Fusce scelerisque vitae erat ultrices luctus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla a commodo sapien, sit amet pharetra nunc. Mauris convallis ut tortor non interdum.

Ut purus mi, aliquam elementum tortor vel, tincidunt ultricies massa. Vivamus eget dictum libero. Cras hendrerit ex cursus sapien ultrices placerat. Duis ut porttitor metus. Praesent erat massa, sodales vel varius vel, fermentum ut massa. Aenean ac semper est. Integer volutpat erat nec turpis tempus, quis euismod augue lobortis. Vestibulum porttitor malesuada diam, eu congue diam consequat nec. Donec elementum felis vel sapien iaculis, non varius justo semper.
    </div>)
}

export default About